[package]
name = "boids"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.6", default-features = false, features = ["png"] }
indicatif = "0.17.11"
rand = "0.9.1"
rayon = "1.10.0"
